### PR TITLE
Introduce possibilty to modify the indexed URLs

### PR DESCRIPTION
**Pull request by marcreichel**
This PR introduces the possibility to modify the URL of a page before it is indexed. This makes it possible to strip away unwanted query parameters for example.

Resolves #21

### CODE REVIEW

**Comment by freekmurze** [comment]
Nice idea!

Looks good, could you also add this to the docs?

**Comment by marcreichel** [comment]
Of course! 🙂 Give me a second 😄 

Any idea about the failed test? Running tests locally works fine.

**Comment by freekmurze** [comment]
I haven't figured out why that one test sometimes fails...

**Comment by marcreichel** [comment]
I've adjusted the docs and added two examples 🙂

**Comment by freekmurze** [comment]
Very nice, thank you!

**Pull request merged**
